name: score_zone
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.7.1
  provider: ^6.0.5
  http: ^1.1.0
  transparent_image: ^2.0.1
  retrofit: ^4.0.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  scrollable_table_view: ^2.0.2
  table_sticky_headers: ^2.0.5
  carousel_slider: ^4.2.1
  wheel_slider: ^1.1.1
  cached_network_image: ^3.3.1
  cached_network_svg_image: ^1.0.0
  jovial_svg: ^1.1.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  retrofit_generator: ^8.0.3
  json_serializable: ^6.7.1
  
flutter:

  uses-material-design: true

  assets:
    - assets/

